title: Learn React
description: React - A JavaScript library for building user interfaces
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: React # add your name
author-img: logo.png # add your photo
about-author: A JavaScript library for building user interfaces
social-twitter: bunlongvan # add your Twitter handle
social-facebook: bunlong.van # add your Facebook handle
social-github: bunlong # add your Github handle
social-linkedin: bunlongvan # add your Linkedin handle
social-email: bunlong.van@gmail.com # add your Email address

# Disqus
discus-identifier: bunlong # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]